sonar.projectKey=NerionSoft_hec-polytechnique-hackathon
sonar.organization=nerionsoft

sonar.projectName=hec-polytechnique-hackathon
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.exclusions=**/node_modules/**,**/.next/**,**/build/**,**/out/**,**/coverage/**,**/*.config.*,**/public/**

sonar.sourceEncoding=UTF-8
